//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PIPS.BOSSSaveAudits {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SaveAuditsServiceSoap", Namespace="http://tempuri.org/")]
    public partial class SaveAuditsService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SaveAuditOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SaveAuditsService() {
            this.Url = "http://localhost:8088/BOSS/Services/SaveAuditsService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SaveAuditCompletedEventHandler SaveAuditCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveAudit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SaveAudit(string clientName, string information, string login, System.DateTime timestamp, string location, double latitude, double longitude, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] picture) {
            this.Invoke("SaveAudit", new object[] {
                        clientName,
                        information,
                        login,
                        timestamp,
                        location,
                        latitude,
                        longitude,
                        picture});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSaveAudit(string clientName, string information, string login, System.DateTime timestamp, string location, double latitude, double longitude, byte[] picture, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SaveAudit", new object[] {
                        clientName,
                        information,
                        login,
                        timestamp,
                        location,
                        latitude,
                        longitude,
                        picture}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndSaveAudit(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void SaveAuditAsync(string clientName, string information, string login, System.DateTime timestamp, string location, double latitude, double longitude, byte[] picture) {
            this.SaveAuditAsync(clientName, information, login, timestamp, location, latitude, longitude, picture, null);
        }
        
        /// <remarks/>
        public void SaveAuditAsync(string clientName, string information, string login, System.DateTime timestamp, string location, double latitude, double longitude, byte[] picture, object userState) {
            if ((this.SaveAuditOperationCompleted == null)) {
                this.SaveAuditOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveAuditOperationCompleted);
            }
            this.InvokeAsync("SaveAudit", new object[] {
                        clientName,
                        information,
                        login,
                        timestamp,
                        location,
                        latitude,
                        longitude,
                        picture}, this.SaveAuditOperationCompleted, userState);
        }
        
        private void OnSaveAuditOperationCompleted(object arg) {
            if ((this.SaveAuditCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveAuditCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void SaveAuditCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591