//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PIPS.BOF2HotlistsStatus {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GetHotlistStatusServiceSoapBinding", Namespace="http://80.177.196.221:8081/bof2/services/GetHotlistStatusService")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(BofHotlistRevisions))]
    public partial class UpdateHotlistsServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getHotlistStatusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UpdateHotlistsServiceService() {
            this.Url = "http://80.177.196.221:8081/bof2/services/GetHotlistStatusService";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getHotlistStatusCompletedEventHandler getHotlistStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://scarab.webservices.bof2.anite.com", ResponseNamespace="http://80.177.196.221:8081/bof2/services/GetHotlistStatusService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getHotlistStatusReturn")]
        public BofHotlistRevisions[] getHotlistStatus(string signatureOfSender, string username, string sourceID) {
            object[] results = this.Invoke("getHotlistStatus", new object[] {
                        signatureOfSender,
                        username,
                        sourceID});
            return ((BofHotlistRevisions[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetHotlistStatus(string signatureOfSender, string username, string sourceID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getHotlistStatus", new object[] {
                        signatureOfSender,
                        username,
                        sourceID}, callback, asyncState);
        }
        
        /// <remarks/>
        public BofHotlistRevisions[] EndgetHotlistStatus(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((BofHotlistRevisions[])(results[0]));
        }
        
        /// <remarks/>
        public void getHotlistStatusAsync(string signatureOfSender, string username, string sourceID) {
            this.getHotlistStatusAsync(signatureOfSender, username, sourceID, null);
        }
        
        /// <remarks/>
        public void getHotlistStatusAsync(string signatureOfSender, string username, string sourceID, object userState) {
            if ((this.getHotlistStatusOperationCompleted == null)) {
                this.getHotlistStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetHotlistStatusOperationCompleted);
            }
            this.InvokeAsync("getHotlistStatus", new object[] {
                        signatureOfSender,
                        username,
                        sourceID}, this.getHotlistStatusOperationCompleted, userState);
        }
        
        private void OngetHotlistStatusOperationCompleted(object arg) {
            if ((this.getHotlistStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getHotlistStatusCompleted(this, new getHotlistStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:GetHotlistStatusService")]
    public partial class BofHotlistRevisions {
        
        private string externalSystemRevisionField;
        
        private string hotlistNameField;
        
        private string latestRevisionField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string externalSystemRevision {
            get {
                return this.externalSystemRevisionField;
            }
            set {
                this.externalSystemRevisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string hotlistName {
            get {
                return this.hotlistNameField;
            }
            set {
                this.hotlistNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string latestRevision {
            get {
                return this.latestRevisionField;
            }
            set {
                this.latestRevisionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void getHotlistStatusCompletedEventHandler(object sender, getHotlistStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getHotlistStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getHotlistStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BofHotlistRevisions[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BofHotlistRevisions[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591