//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PIPS.BOF2HotlistsRepoStatus {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GetHotlistRepoStatusServiceSoapBinding", Namespace="http://80.177.196.221:8081/bof2/services/GetHotlistRepoStatusService")]
    public partial class UpdateHotlistsServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getRepoStatusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UpdateHotlistsServiceService() {
            this.Url = "http://80.177.196.221:8081/bof2/services/GetHotlistRepoStatusService";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getRepoStatusCompletedEventHandler getRepoStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://scarab.webservices.bof2.anite.com", ResponseNamespace="http://80.177.196.221:8081/bof2/services/GetHotlistRepoStatusService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getRepoStatusReturn")]
        public long getRepoStatus(string signatureOfSender, string username, string sourceID, long revNumber) {
            object[] results = this.Invoke("getRepoStatus", new object[] {
                        signatureOfSender,
                        username,
                        sourceID,
                        revNumber});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetRepoStatus(string signatureOfSender, string username, string sourceID, long revNumber, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getRepoStatus", new object[] {
                        signatureOfSender,
                        username,
                        sourceID,
                        revNumber}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndgetRepoStatus(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void getRepoStatusAsync(string signatureOfSender, string username, string sourceID, long revNumber) {
            this.getRepoStatusAsync(signatureOfSender, username, sourceID, revNumber, null);
        }
        
        /// <remarks/>
        public void getRepoStatusAsync(string signatureOfSender, string username, string sourceID, long revNumber, object userState) {
            if ((this.getRepoStatusOperationCompleted == null)) {
                this.getRepoStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRepoStatusOperationCompleted);
            }
            this.InvokeAsync("getRepoStatus", new object[] {
                        signatureOfSender,
                        username,
                        sourceID,
                        revNumber}, this.getRepoStatusOperationCompleted, userState);
        }
        
        private void OngetRepoStatusOperationCompleted(object arg) {
            if ((this.getRepoStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRepoStatusCompleted(this, new getRepoStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void getRepoStatusCompletedEventHandler(object sender, getRepoStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRepoStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRepoStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591