//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PIPS.BOF2SetHotlistsStatus {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SetHotlistStatusServiceSoapBinding", Namespace="http://87.83.239.76:8080/bof2/services/SetHotlistStatusService")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ExternalHotlistRevisions))]
    public partial class SetHotlistStatusServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback setBeanNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback setHotlistStatusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SetHotlistStatusServiceService() {
            this.Url = "http://87.83.239.76:8080/bof2/services/SetHotlistStatusService";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event setBeanNameCompletedEventHandler setBeanNameCompleted;
        
        /// <remarks/>
        public event setHotlistStatusCompletedEventHandler setHotlistStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://bof2.pipstechnology.com", ResponseNamespace="http://87.83.239.76:8080/bof2/services/SetHotlistStatusService")]
        public void setBeanName(string beanName) {
            this.Invoke("setBeanName", new object[] {
                        beanName});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetBeanName(string beanName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setBeanName", new object[] {
                        beanName}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndsetBeanName(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void setBeanNameAsync(string beanName) {
            this.setBeanNameAsync(beanName, null);
        }
        
        /// <remarks/>
        public void setBeanNameAsync(string beanName, object userState) {
            if ((this.setBeanNameOperationCompleted == null)) {
                this.setBeanNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetBeanNameOperationCompleted);
            }
            this.InvokeAsync("setBeanName", new object[] {
                        beanName}, this.setBeanNameOperationCompleted, userState);
        }
        
        private void OnsetBeanNameOperationCompleted(object arg) {
            if ((this.setBeanNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setBeanNameCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://bof2.pipstechnology.com", ResponseNamespace="http://87.83.239.76:8080/bof2/services/SetHotlistStatusService")]
        public void setHotlistStatus(string signatureOfSender, string username, string sourceId, ExternalHotlistRevisions[] hotlistsAndRevisions) {
            this.Invoke("setHotlistStatus", new object[] {
                        signatureOfSender,
                        username,
                        sourceId,
                        hotlistsAndRevisions});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetHotlistStatus(string signatureOfSender, string username, string sourceId, ExternalHotlistRevisions[] hotlistsAndRevisions, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setHotlistStatus", new object[] {
                        signatureOfSender,
                        username,
                        sourceId,
                        hotlistsAndRevisions}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndsetHotlistStatus(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void setHotlistStatusAsync(string signatureOfSender, string username, string sourceId, ExternalHotlistRevisions[] hotlistsAndRevisions) {
            this.setHotlistStatusAsync(signatureOfSender, username, sourceId, hotlistsAndRevisions, null);
        }
        
        /// <remarks/>
        public void setHotlistStatusAsync(string signatureOfSender, string username, string sourceId, ExternalHotlistRevisions[] hotlistsAndRevisions, object userState) {
            if ((this.setHotlistStatusOperationCompleted == null)) {
                this.setHotlistStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetHotlistStatusOperationCompleted);
            }
            this.InvokeAsync("setHotlistStatus", new object[] {
                        signatureOfSender,
                        username,
                        sourceId,
                        hotlistsAndRevisions}, this.setHotlistStatusOperationCompleted, userState);
        }
        
        private void OnsetHotlistStatusOperationCompleted(object arg) {
            if ((this.setHotlistStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setHotlistStatusCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:SetHotlistStatusService")]
    public partial class ExternalHotlistRevisions {
        
        private string currentRevisionField;
        
        private string hotlistNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string currentRevision {
            get {
                return this.currentRevisionField;
            }
            set {
                this.currentRevisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string hotlistName {
            get {
                return this.hotlistNameField;
            }
            set {
                this.hotlistNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void setBeanNameCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void setHotlistStatusCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591