//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PIPS.BOF2PNCFastTrackResponses {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PNCFastTrackResponsesWebServiceSoapBinding", Namespace="http://80.177.196.221:8081/bof2/services/PNCFastTrackResponsesWebService")]
    public partial class PNCWebServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback fastTrackResponsesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PNCWebServiceService() {
            this.Url = "http://80.177.196.221:8081/bof2/services/PNCFastTrackResponsesWebService";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event fastTrackResponsesCompletedEventHandler fastTrackResponsesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://pnc.webservices.bof2.anite.com", ResponseNamespace="http://80.177.196.221:8081/bof2/services/PNCFastTrackResponsesWebService")]
        [return: System.Xml.Serialization.SoapElementAttribute("fastTrackResponsesReturn")]
        public object[] fastTrackResponses(string signature, string username, int sourceIdentifier) {
            object[] results = this.Invoke("fastTrackResponses", new object[] {
                        signature,
                        username,
                        sourceIdentifier});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfastTrackResponses(string signature, string username, int sourceIdentifier, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fastTrackResponses", new object[] {
                        signature,
                        username,
                        sourceIdentifier}, callback, asyncState);
        }
        
        /// <remarks/>
        public object[] EndfastTrackResponses(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void fastTrackResponsesAsync(string signature, string username, int sourceIdentifier) {
            this.fastTrackResponsesAsync(signature, username, sourceIdentifier, null);
        }
        
        /// <remarks/>
        public void fastTrackResponsesAsync(string signature, string username, int sourceIdentifier, object userState) {
            if ((this.fastTrackResponsesOperationCompleted == null)) {
                this.fastTrackResponsesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfastTrackResponsesOperationCompleted);
            }
            this.InvokeAsync("fastTrackResponses", new object[] {
                        signature,
                        username,
                        sourceIdentifier}, this.fastTrackResponsesOperationCompleted, userState);
        }
        
        private void OnfastTrackResponsesOperationCompleted(object arg) {
            if ((this.fastTrackResponsesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fastTrackResponsesCompleted(this, new fastTrackResponsesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void fastTrackResponsesCompletedEventHandler(object sender, fastTrackResponsesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fastTrackResponsesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fastTrackResponsesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591