//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PIPS.BOF2PNCManualCheck2 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PNCManualCheckWebServiceSoapBinding", Namespace="http://192.168.2.3:8081/bof2/services/PNCManualCheckWebService")]
    public partial class PNCWebServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback manualCheckOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PNCWebServiceService() {
            this.Url = "http://192.168.2.3:8081/bof2/services/PNCManualCheckWebService";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event manualCheckCompletedEventHandler manualCheckCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://pnc.webservices.bof2.anite.com", ResponseNamespace="http://192.168.2.3:8081/bof2/services/PNCManualCheckWebService")]
        [return: System.Xml.Serialization.SoapElementAttribute("manualCheckReturn")]
        public object manualCheck(string signature, string username, int reasonCode, string vrm, short sourceId) {
            object[] results = this.Invoke("manualCheck", new object[] {
                        signature,
                        username,
                        reasonCode,
                        vrm,
                        sourceId});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmanualCheck(string signature, string username, int reasonCode, string vrm, short sourceId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("manualCheck", new object[] {
                        signature,
                        username,
                        reasonCode,
                        vrm,
                        sourceId}, callback, asyncState);
        }
        
        /// <remarks/>
        public object EndmanualCheck(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void manualCheckAsync(string signature, string username, int reasonCode, string vrm, short sourceId) {
            this.manualCheckAsync(signature, username, reasonCode, vrm, sourceId, null);
        }
        
        /// <remarks/>
        public void manualCheckAsync(string signature, string username, int reasonCode, string vrm, short sourceId, object userState) {
            if ((this.manualCheckOperationCompleted == null)) {
                this.manualCheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmanualCheckOperationCompleted);
            }
            this.InvokeAsync("manualCheck", new object[] {
                        signature,
                        username,
                        reasonCode,
                        vrm,
                        sourceId}, this.manualCheckOperationCompleted, userState);
        }
        
        private void OnmanualCheckOperationCompleted(object arg) {
            if ((this.manualCheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.manualCheckCompleted(this, new manualCheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void manualCheckCompletedEventHandler(object sender, manualCheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class manualCheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal manualCheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591