//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PIPS.BOF2HotlistsUpdatesRestrictSize {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GetHotlistsUpdatesRestrictedSizeServiceSoapBinding", Namespace="http://87.83.239.76:8080/bof2/services/GetHotlistsUpdatesRestrictedSizeService")]
    public partial class GetHotlistsUpdatesRestrictedSizeServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback setBeanNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback getHotlistUpdatesRestrictSizeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GetHotlistsUpdatesRestrictedSizeServiceService() {
            this.Url = "http://87.83.239.76:8080/bof2/services/GetHotlistsUpdatesRestrictedSizeService";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event setBeanNameCompletedEventHandler setBeanNameCompleted;
        
        /// <remarks/>
        public event getHotlistUpdatesRestrictSizeCompletedEventHandler getHotlistUpdatesRestrictSizeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://bof2.pipstechnology.com", ResponseNamespace="http://87.83.239.76:8080/bof2/services/GetHotlistsUpdatesRestrictedSizeService")]
        public void setBeanName(string beanName) {
            this.Invoke("setBeanName", new object[] {
                        beanName});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetBeanName(string beanName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setBeanName", new object[] {
                        beanName}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndsetBeanName(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void setBeanNameAsync(string beanName) {
            this.setBeanNameAsync(beanName, null);
        }
        
        /// <remarks/>
        public void setBeanNameAsync(string beanName, object userState) {
            if ((this.setBeanNameOperationCompleted == null)) {
                this.setBeanNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetBeanNameOperationCompleted);
            }
            this.InvokeAsync("setBeanName", new object[] {
                        beanName}, this.setBeanNameOperationCompleted, userState);
        }
        
        private void OnsetBeanNameOperationCompleted(object arg) {
            if ((this.setBeanNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setBeanNameCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://bof2.pipstechnology.com", ResponseNamespace="http://87.83.239.76:8080/bof2/services/GetHotlistsUpdatesRestrictedSizeService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getHotlistUpdatesRestrictSizeReturn")]
        public BofHotlistData getHotlistUpdatesRestrictSize(string signatureOfSender, string username, string sourceId, string hotlistName, int size) {
            object[] results = this.Invoke("getHotlistUpdatesRestrictSize", new object[] {
                        signatureOfSender,
                        username,
                        sourceId,
                        hotlistName,
                        size});
            return ((BofHotlistData)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetHotlistUpdatesRestrictSize(string signatureOfSender, string username, string sourceId, string hotlistName, int size, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getHotlistUpdatesRestrictSize", new object[] {
                        signatureOfSender,
                        username,
                        sourceId,
                        hotlistName,
                        size}, callback, asyncState);
        }
        
        /// <remarks/>
        public BofHotlistData EndgetHotlistUpdatesRestrictSize(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((BofHotlistData)(results[0]));
        }
        
        /// <remarks/>
        public void getHotlistUpdatesRestrictSizeAsync(string signatureOfSender, string username, string sourceId, string hotlistName, int size) {
            this.getHotlistUpdatesRestrictSizeAsync(signatureOfSender, username, sourceId, hotlistName, size, null);
        }
        
        /// <remarks/>
        public void getHotlistUpdatesRestrictSizeAsync(string signatureOfSender, string username, string sourceId, string hotlistName, int size, object userState) {
            if ((this.getHotlistUpdatesRestrictSizeOperationCompleted == null)) {
                this.getHotlistUpdatesRestrictSizeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetHotlistUpdatesRestrictSizeOperationCompleted);
            }
            this.InvokeAsync("getHotlistUpdatesRestrictSize", new object[] {
                        signatureOfSender,
                        username,
                        sourceId,
                        hotlistName,
                        size}, this.getHotlistUpdatesRestrictSizeOperationCompleted, userState);
        }
        
        private void OngetHotlistUpdatesRestrictSizeOperationCompleted(object arg) {
            if ((this.getHotlistUpdatesRestrictSizeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getHotlistUpdatesRestrictSizeCompleted(this, new getHotlistUpdatesRestrictSizeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:GetHotlistsUpdatesRestrictedSizeService")]
    public partial class BofHotlistData {
        
        private bool fileTooBigField;
        
        private byte[] hotlistDeltasField;
        
        private string hotlistNameField;
        
        private string latestRevisionField;
        
        /// <remarks/>
        public bool fileTooBig {
            get {
                return this.fileTooBigField;
            }
            set {
                this.fileTooBigField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] hotlistDeltas {
            get {
                return this.hotlistDeltasField;
            }
            set {
                this.hotlistDeltasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string hotlistName {
            get {
                return this.hotlistNameField;
            }
            set {
                this.hotlistNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string latestRevision {
            get {
                return this.latestRevisionField;
            }
            set {
                this.latestRevisionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void setBeanNameCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void getHotlistUpdatesRestrictSizeCompletedEventHandler(object sender, getHotlistUpdatesRestrictSizeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getHotlistUpdatesRestrictSizeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getHotlistUpdatesRestrictSizeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BofHotlistData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BofHotlistData)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591