//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PIPS.BOSSSaveEvents {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SaveEventsServiceSoap", Namespace="http://tempuri.org/")]
    public partial class SaveEventsService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SaveEventPatchOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveEventOverviewOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveEventOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SaveEventsService() {
            this.Url = "http://localhost:8088/BOSS/Services/SaveEventsService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SaveEventPatchCompletedEventHandler SaveEventPatchCompleted;
        
        /// <remarks/>
        public event SaveEventOverviewCompletedEventHandler SaveEventOverviewCompleted;
        
        /// <remarks/>
        public event SaveEventCompletedEventHandler SaveEventCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveEventPatch", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SaveEventPatch(string clientName, long read_id, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] patch) {
            this.Invoke("SaveEventPatch", new object[] {
                        clientName,
                        read_id,
                        patch});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSaveEventPatch(string clientName, long read_id, byte[] patch, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SaveEventPatch", new object[] {
                        clientName,
                        read_id,
                        patch}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndSaveEventPatch(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void SaveEventPatchAsync(string clientName, long read_id, byte[] patch) {
            this.SaveEventPatchAsync(clientName, read_id, patch, null);
        }
        
        /// <remarks/>
        public void SaveEventPatchAsync(string clientName, long read_id, byte[] patch, object userState) {
            if ((this.SaveEventPatchOperationCompleted == null)) {
                this.SaveEventPatchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveEventPatchOperationCompleted);
            }
            this.InvokeAsync("SaveEventPatch", new object[] {
                        clientName,
                        read_id,
                        patch}, this.SaveEventPatchOperationCompleted, userState);
        }
        
        private void OnSaveEventPatchOperationCompleted(object arg) {
            if ((this.SaveEventPatchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveEventPatchCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveEventOverview", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SaveEventOverview(string clientName, long read_id, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] overview) {
            this.Invoke("SaveEventOverview", new object[] {
                        clientName,
                        read_id,
                        overview});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSaveEventOverview(string clientName, long read_id, byte[] overview, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SaveEventOverview", new object[] {
                        clientName,
                        read_id,
                        overview}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndSaveEventOverview(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void SaveEventOverviewAsync(string clientName, long read_id, byte[] overview) {
            this.SaveEventOverviewAsync(clientName, read_id, overview, null);
        }
        
        /// <remarks/>
        public void SaveEventOverviewAsync(string clientName, long read_id, byte[] overview, object userState) {
            if ((this.SaveEventOverviewOperationCompleted == null)) {
                this.SaveEventOverviewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveEventOverviewOperationCompleted);
            }
            this.InvokeAsync("SaveEventOverview", new object[] {
                        clientName,
                        read_id,
                        overview}, this.SaveEventOverviewOperationCompleted, userState);
        }
        
        private void OnSaveEventOverviewOperationCompleted(object arg) {
            if ((this.SaveEventOverviewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveEventOverviewCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveEvent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long SaveEvent(string clientName, Read read) {
            object[] results = this.Invoke("SaveEvent", new object[] {
                        clientName,
                        read});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSaveEvent(string clientName, Read read, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SaveEvent", new object[] {
                        clientName,
                        read}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndSaveEvent(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void SaveEventAsync(string clientName, Read read) {
            this.SaveEventAsync(clientName, read, null);
        }
        
        /// <remarks/>
        public void SaveEventAsync(string clientName, Read read, object userState) {
            if ((this.SaveEventOperationCompleted == null)) {
                this.SaveEventOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveEventOperationCompleted);
            }
            this.InvokeAsync("SaveEvent", new object[] {
                        clientName,
                        read}, this.SaveEventOperationCompleted, userState);
        }
        
        private void OnSaveEventOperationCompleted(object arg) {
            if ((this.SaveEventCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveEventCompleted(this, new SaveEventCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Read {
        
        private Hit[] hitsField;
        
        private string vrmField;
        
        private string loginField;
        
        private int confidenceField;
        
        private System.DateTime timestampField;
        
        private string syntaxField;
        
        private string locationField;
        
        private byte[] overviewField;
        
        private byte[] patchField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private bool misreadField;
        
        /// <remarks/>
        public Hit[] Hits {
            get {
                return this.hitsField;
            }
            set {
                this.hitsField = value;
            }
        }
        
        /// <remarks/>
        public string Vrm {
            get {
                return this.vrmField;
            }
            set {
                this.vrmField = value;
            }
        }
        
        /// <remarks/>
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public int Confidence {
            get {
                return this.confidenceField;
            }
            set {
                this.confidenceField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        public string Syntax {
            get {
                return this.syntaxField;
            }
            set {
                this.syntaxField = value;
            }
        }
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Overview {
            get {
                return this.overviewField;
            }
            set {
                this.overviewField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Patch {
            get {
                return this.patchField;
            }
            set {
                this.patchField = value;
            }
        }
        
        /// <remarks/>
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public bool Misread {
            get {
                return this.misreadField;
            }
            set {
                this.misreadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Hit {
        
        private string hotListField;
        
        private string vRMField;
        
        private string field1Field;
        
        private string field2Field;
        
        private string field3Field;
        
        private string field4Field;
        
        private string field5Field;
        
        private string pNCIDField;
        
        private string informationField;
        
        /// <remarks/>
        public string HotList {
            get {
                return this.hotListField;
            }
            set {
                this.hotListField = value;
            }
        }
        
        /// <remarks/>
        public string VRM {
            get {
                return this.vRMField;
            }
            set {
                this.vRMField = value;
            }
        }
        
        /// <remarks/>
        public string Field1 {
            get {
                return this.field1Field;
            }
            set {
                this.field1Field = value;
            }
        }
        
        /// <remarks/>
        public string Field2 {
            get {
                return this.field2Field;
            }
            set {
                this.field2Field = value;
            }
        }
        
        /// <remarks/>
        public string Field3 {
            get {
                return this.field3Field;
            }
            set {
                this.field3Field = value;
            }
        }
        
        /// <remarks/>
        public string Field4 {
            get {
                return this.field4Field;
            }
            set {
                this.field4Field = value;
            }
        }
        
        /// <remarks/>
        public string Field5 {
            get {
                return this.field5Field;
            }
            set {
                this.field5Field = value;
            }
        }
        
        /// <remarks/>
        public string PNCID {
            get {
                return this.pNCIDField;
            }
            set {
                this.pNCIDField = value;
            }
        }
        
        /// <remarks/>
        public string Information {
            get {
                return this.informationField;
            }
            set {
                this.informationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void SaveEventPatchCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void SaveEventOverviewCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void SaveEventCompletedEventHandler(object sender, SaveEventCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveEventCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveEventCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591